### ISSUE TITLE
Android-6/CM13 rooted: How can I grant write&delete access ?

### ISSUE THREAD

**Issue by herrdeh** [k3b/APhotoManager#80] opened 2017-04-09 17:39 UTC
I can neither copy, nor delete any photo from within this app, neither from the external, not the internal SD card. What can I do?

I'm using CM13 (Android 6), the phone is rooted.

**Comment by k3b** [comment] 2017-04-10 06:42
Unfortunatly i only have a android 4.4 and an android-4.2 device and no CM so i cannot help you.

I assume this issue is realated to #61 .  May be community can help.

**Comment by k3b** [comment] 2018-11-28 09:20
closed as duplicate of #95

**Closed by k3b** 2018-11-28 09:20 UTC
Labels: help wanted, mod file operations, permissions, question, waiting for feedback
