### ISSUE TITLE
Ability to reset the media database

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#46] opened 2016-05-15 09:45 UTC
- On the first open it displayed correctly the photos I might wanted to see (WhatsApp, screenshots, own pictures)
- When adding/removing some pictures, the tile screen is not updated (#43)
- I thought 'lets run the media scanner, that might solve the issue'. Instead it started adding useless app-images (smileys etc) from Telegram and other apps (probably due to #44)
- **Now I'm in the situation where I'd like to delete the media database and start as if it were a 'new install' of APM. It would be nice to be able to do this from the settings.**

**Comment by k3b** [comment] 2016-05-17 11:13
Closed as duplicate of #36: This is a side effect of #36 - APhotoManager 0.4.6 and older is currently not obeying the ".nomedia" folders. Rescan " started adding useless app-images (smileys etc) from Telegram and other apps"

APhotoManager 0.4.7 should repair and fix this.

**Closed by k3b** 2016-05-17 11:13 UTC
Labels: bug, duplicate
