### ISSUE TITLE
can't write secondary storage(removable SD card)

### ISSUE THREAD

**Issue by 025nju** [k3b/APhotoManager#201] opened 2022-08-19 14:35 UTC
**Describe the bug**
can't write secondary storage(removable SD card). Works good if the picture is on external storage of the handset(not removable SD card). 

**To Reproduce**
1. Go to 'edit exif' and edit the metadata of a picture which is stored on removable SD card.
2. Click on '√'
3. See message like "updated 0 files"

**Expected behavior**
the change can be saved successfully

**Smartphone (please complete the following information):**
 - Android version: 9.1
 - [A Photo Manager Version] :0.8.3.200315

**Comment by k3b** [comment] 2022-08-19 15:00
closed as duplicate of #169

**Closed as completed by k3b** 2022-08-19 15:00 UTC
