### ISSUE TITLE
Invalid SQL message on GrapheneOS, Pixel 3a

### ISSUE THREAD

**Issue by rubensz** [k3b/APhotoManager#161] opened 2020-01-01 17:10 UTC
I love this app! 
Having trouble setting it up on my new phone. Have no idea what is wrong, any suggestions would be greatly appreciated! 

I've searched the issues section but couldn't find anything on this problem. 

When I try to open A Photo Manager app I get an Invalid SQL message that won't go away when i click "OK". The app just locks up and I can't do anything. 

`
Invaldi SQL. Reloading Default.
SQL error 'Invalid Column max(width,height) AS col_width'
SELECT _id, _data AS disp_txt, max(width,height) AS col_width, longitude, datetaken, _data, orientation FROM content://media/external/file
WHERE ((media_type = 1 ))
`

![Screenshot_20200101-173936](https://user-images.githubusercontent.com/13224717/71643842-fb50b400-2cbe-11ea-93e5-ddd801294824.png)

**Smartphone:**
 - GrapheneOS for Pixel 3a (Sargo) [e.g. Android-10] :
 - [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) Version 0.8.0.191021

**Comment by k3b** [comment] 2020-01-09 12:28
Closed as duplicate of https://github.com/k3b/APhotoManager/issues/155 "Unuseable On Android 10, sql error".

Re-implementation is under way.

**Closed by k3b** 2020-01-09 12:28 UTC
