### ISSUE TITLE
a dialog with sql statements appears

### ISSUE THREAD

**Issue by anlalalu** [k3b/APhotoManager#159] opened 2019-12-19 13:40 UTC
**Describe the bug**
a dialog with sql statements appears when operating in GalleryFilterActivity

**To Reproduce**
1. tap 'more options'
2. tap 'Filter'
3. text in invalid date
4. tap 'more options'
5. tap 'Details'

**Expected behavior**

dialog with some information rather than sql statements

**Smartphone (please complete the following information):**
 - Android version [e.g. Android-7.1] : 4.4.4
 - [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (i.e. 0.4.6.160304) :v0.8.0.191021

**Additional context**
![image](https://user-images.githubusercontent.com/46981872/71177942-0f041f80-22a8-11ea-8963-38a9ded1f700.png)

**Crash Report**
If you report an app crash: Can you add the crash logfile to this ticket?

E/k3bFoto: GalF-'234' is not a valid date.
                                          java.lang.RuntimeException: '234' is not a valid date.
                                              at de.k3b.android.androFotoFinder.GalleryFilterActivity$FilterValue.convertDate(GalleryFilterActivity.java:730)
                                              at de.k3b.android.androFotoFinder.GalleryFilterActivity$FilterValue.getDateMin(GalleryFilterActivity.java:618)
                                              at de.k3b.io.GalleryFilterParameter.get(GalleryFilterParameter.java:66)
                                              at de.k3b.io.GalleryFilterParameter.get(GalleryFilterParameter.java:36)
                                              at de.k3b.android.androFotoFinder.GalleryFilterActivity.fromGui(GalleryFilterActivity.java:743)
                                              at de.k3b.android.androFotoFinder.GalleryFilterActivity.getAsGalleryFilter(GalleryFilterActivity.java:334)
                                              at de.k3b.android.androFotoFinder.GalleryFilterActivity.getAsMergedQuery(GalleryFilterActivity.java:339)
                                              at de.k3b.android.androFotoFinder.GalleryFilterActivity.cmdShowDetails(GalleryFilterActivity.java:754)
                                              at de.k3b.android.androFotoFinder.GalleryFilterActivity.onOptionsItemSelected(GalleryFilterActivity.java:300)
                                              at android.app.Activity.onMenuItemSelected(Activity.java:2600)
                                              at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1012)
                                              at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:741)
                                              at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                              at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:884)
                                              at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
                                              at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
                                              at android.widget.AdapterView.performItemClick(AdapterView.java:299)
                                              at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
                                              at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
                                              at android.widget.AbsListView.onTouchUp(AbsListView.java:3657)
                                              at android.widget.AbsListView.onTouchEvent(AbsListView.java:3436)
                                              at android.view.View.dispatchTouchEvent(View.java:7706)
                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                              at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1633)
                                              at android.view.View.dispatchPointerEvent(View.java:7886)
                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                              at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5532)
                                              at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5512)
                                              at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5483)
                                              at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5612)
                                              at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                              at android.os.MessageQueue.nativePollOnce(Native Method)
                                              at android.os.MessageQueue.next(MessageQueue.java:138)
                                              at android.os.Looper.loop(Looper.java:123)
                                              at android.app.ActivityThread.main(ActivityThread.java:5001)

**Comment by anlalalu** [comment] 2019-12-31 02:49
This can also be reproduced in Android 7.1.0.
Do you consider it as a defect? @k3b

**Comment by k3b** [comment] 2020-01-09 13:13
@anlalalu Thanks for spending time to find errors in the app.

In my point of view the errorlog "'234' is not a valid date."  is a minor defect as error-checking of input-fields is not caught on device rotation. "minor" means it does not prevent users from using the app.

Note: When you tap on 'Details' you will always get the dialog with sql statements no matter if there is an error or not.

Fixing this has to wait until architecture re-implementation for android-10 #155 has finished which will take some time.

**Comment by k3b** [comment] 2020-02-06 04:14
closed as duplicate of #158

**Closed by k3b** 2020-02-06 04:14 UTC
Labels: minor-bug
