### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by Kratsac** [k3b/APhotoManager#55] opened 2016-07-13 09:12 UTC
### Expected behavior

...Display pictures correctly according to their orientation

### Actual behavior

Portrait Format is mainly displayed as landscape both in gallery-view as well as in image-view mode.

### Environment

* Android Version (i.e. 5.1):
  * ...
* [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (0.5.0.160629) :

**Comment by k3b** [comment] 2016-07-13 14:40
Thanks for reporting. This is a new bug introduced with #54

**Comment by Kratsac** [comment] 2016-07-14 07:14
Somehow, the new version isn't provided via fdriod to me. Don't know why. As soon as I will have tested, I let you know.
Thanks.

**Comment by k3b** [comment] 2016-07-15 10:40
i have analysed the problem. 

* With version 0.5.0 and below gallery-view-thumbnail and imagedetail-view havent respected exif-orientation. consistent but wrong
* with 0.5.1 the thumbnail has correct exif-orientation but in imagedetail-view it is not. so with 0.5.1. the problem is more obvious :-)

To fix i have to make changes in in support library

**Comment by Kratsac** [comment] 2016-07-26 14:04
Checked it with 0.5.1, works fine now. THANKS!

**Comment by k3b** [comment] 2016-07-26 14:16
thanks for testing. with 0.5.1 galleryview is ok but the detail-view does not respect orientation in 0.5.1. this should be fixed with 0.5.2

**Closed by k3b** 2016-07-26 14:16 UTC
Labels: bug, mod gallery, mod image view
